{"hierarchy":{"paths":[["doc:\/\/SwiftKyber\/documentation\/SwiftKyber","doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Wrong cipher text size"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftkyber\/exception\/ciphertextsize(value:)"]}],"metadata":{"role":"symbol","title":"Exception.cipherTextSize(value:)","roleHeading":"Case","symbolKind":"case","modules":[{"name":"SwiftKyber"}],"externalID":"s:10SwiftKyber9ExceptionO14cipherTextSizeyACSi_tcACmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cipherTextSize","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception\/cipherTextSize(value:)"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cipherTextSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://SwiftKyber/documentation/SwiftKyber":{"url":"\/documentation\/swiftkyber","abstract":[{"text":"Module-Lattice-Based Key-Encapsulation Mechanism Standard","type":"text"}],"title":"SwiftKyber","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber"},"doc://SwiftKyber/documentation/SwiftKyber/Exception/cipherTextSize(value:)":{"url":"\/documentation\/swiftkyber\/exception\/ciphertextsize(value:)","abstract":[{"type":"text","text":"Wrong cipher text size"}],"identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception\/cipherTextSize(value:)","type":"topic","role":"symbol","title":"Exception.cipherTextSize(value:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cipherTextSize","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://SwiftKyber/documentation/SwiftKyber/Exception":{"type":"topic","url":"\/documentation\/swiftkyber\/exception","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Exception","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Exception"}],"title":"Exception","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/Exception","abstract":[{"type":"text","text":"The Kyber exceptions"}]}}}